spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.52pojie.cn
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: http://www.51cto.com
          predicates:
            - Query=url,qq